version: '3.3'
services:
  spring-docker:
    container_name: spring-docker-backend
    build: ./hulkstore
    ports:
      - '8088:8080'
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
