apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-docker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: postgres-docker
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: postgres-docker
        image: myakscluster07.azurecr.io/postgres:v2
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-docker
spec:
  type: LoadBalancer
  ports:
  - port: 5432
  selector:
    app: postgres-docker
